const OptionsManagerV2 = artifacts.require("OptionsManagerV2");
const OptionsPool = artifacts.require("OptionsPoolTest");
const imVolatility32 = artifacts.require("imVolatility32");
const OptionsPrice = artifacts.require("OptionsPrice");
let FNXCoin = artifacts.require("FNXCoin");
const BN = require("bn.js");
let month = 30*60*60*24;
let collateral0 = "0x0000000000000000000000000000000000000000";
let testFunc = require("./testFunction.js")
let FNXMinePool = artifacts.require("FNXMinePool");
contract('OptionsManagerV2', function (accounts){
    it('OptionsManagerV2 redeem collateral', async function (){
        let volInstance = await imVolatility32.deployed();
        await testFunc.AddImpliedVolatility(volInstance,false);
        let OptionsManger = await OptionsManagerV2.deployed();
        let options = await OptionsPool.deployed();
        let fnx = await FNXCoin.deployed();
        let tx = await OptionsManger.addWhiteList(collateral0);
//        console.log(tx);
        tx = await OptionsManger.addWhiteList(fnx.address);
        await options.addUnderlyingAsset(1);
        let minePool = await FNXMinePool.deployed();
//        console.log(tx);
//        return;
        await OptionsManger.addWhiteList(fnx.address);
        await fnx.approve(OptionsManger.address,10000000000000);
        await OptionsManger.addCollateral(fnx.address,10000000000000);
        await OptionsManger.redeemCollateral(498500000000000,collateral0);
    });
    it('OptionsManagerV2 add collateral', async function (){
        let volInstance = await imVolatility32.deployed();
        await testFunc.AddImpliedVolatility(volInstance,false);
        let OptionsManger = await OptionsManagerV2.deployed();
        let options = await OptionsPool.deployed();
        let fnx = await FNXCoin.deployed();
        let tx = await OptionsManger.addWhiteList(collateral0);
//        console.log(tx);
        tx = await OptionsManger.addWhiteList(fnx.address);
        await options.addUnderlyingAsset(1);
        let minePool = await FNXMinePool.deployed();
//        console.log(tx);
//        return;
        await OptionsManger.addWhiteList(fnx.address);
        await OptionsManger.addCollateral(collateral0,10000000000000,{value : 10000000000000});
        let minebalance = await minePool.getMinerBalance(accounts[0],collateral0);
        console.log(33333333333333,minebalance.toString(10));
        minebalance = await minePool.getMinerBalance(accounts[0],fnx.address);
        console.log(33333333333333,minebalance.toString(10));
        for (var i=0;i<100;i++){
                await options.addExpiration(month);
        }
        await OptionsManger.addCollateral(collateral0,10000000000000,{from : accounts[1],value : 10000000000000});
        minebalance = await minePool.getMinerBalance(accounts[0],collateral0);
        console.log(33333333333333,minebalance.toString(10));
        minebalance = await minePool.getMinerBalance(accounts[0],fnx.address);
        console.log(33333333333333,minebalance.toString(10));
        for (var i=0;i<100;i++){
                await options.addExpiration(month);
        }
        await fnx.approve(OptionsManger.address,10000000000000);
        await OptionsManger.addCollateral(fnx.address,10000000000000);
        let result = await options.getTotalOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTotalCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getLeftCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTokenNetworth();
        console.log("1-----------------------------------",result.toString(10));

        minebalance = await minePool.getMinerBalance(accounts[0],collateral0);
        console.log(33333333333333,minebalance.toString(10));
        minebalance = await minePool.getMinerBalance(accounts[0],fnx.address);
        console.log(33333333333333,minebalance.toString(10));
        minebalance = await minePool.getMinerBalance(accounts[1],collateral0);
        console.log(44444444444444,minebalance.toString(10));
        minebalance = await minePool.getMinerBalance(accounts[1],fnx.address);
        console.log(44444444444444,minebalance.toString(10));

//        fnx.approve(OptionsManger.address,1000000000000000);
//        tx = await OptionsManger.buyOption(fnx.address,1000000000000000,20000000000,1,month,10000000000,0);
//        console.log(tx)
       
        tx = await OptionsManger.buyOption(collateral0,1000000000000000,20000000000,1,month,10000000000,0,{value : 1000000000000000});
//        console.log(tx);
        tx = await OptionsManger.buyOption(collateral0,1000000000000000,20000000000,1,month,10000000000,0,{value : 1000000000000000});
//        console.log(tx);
        tx = await OptionsManger.buyOption(collateral0,200000000000000,10000000000,1,month,10000000000,0,{value : 200000000000000});
//        console.log(tx);
        result = await options.getTotalOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTotalCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getLeftCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTokenNetworth();
        console.log("2-----------------------------------",result.toString(10));
        result = await options.getOptionsById(1);
        console.log(result[0].toString(10),result[1],result[2].toString(10),result[3].toString(10),result[4].toString(10),result[5].toString(10),result[6].toString(10));
        result = await options.getOptionsById(2);
        console.log(result[0].toString(10),result[1],result[2].toString(10),result[3].toString(10),result[4].toString(10),result[5].toString(10),result[6].toString(10));
        result = await options.getOptionsById(3);
        console.log(result[0].toString(10),result[1],result[2].toString(10),result[3].toString(10),result[4].toString(10),result[5].toString(10),result[6].toString(10));
//        tx = await OptionsManger.sellOption(1,10000000000);
//        console.log(tx);
//        tx = await OptionsManger.exerciseOption(3,10000000000);
        result = await options.getOptionsById(1);
        console.log(result[0].toString(10),result[1],result[2].toString(10),result[3].toString(10),result[4].toString(10),result[5].toString(10),result[6].toString(10));
        result = await options.getOptionsById(2);
        console.log(result[0].toString(10),result[1],result[2].toString(10),result[3].toString(10),result[4].toString(10),result[5].toString(10),result[6].toString(10));
        result = await options.getOptionsById(3);
        console.log(result[0].toString(10),result[1],result[2].toString(10),result[3].toString(10),result[4].toString(10),result[5].toString(10),result[6].toString(10));
//        console.log(tx);
        result = await options.getTotalOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTotalCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getLeftCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTokenNetworth();
        console.log("3-----------------------------------",result.toString(10));
        let optionsLen = await options.getOptionPhaseCalRange();
        console.log(optionsLen[0].toString(10),optionsLen[1].toString(10),optionsLen[2].toString(10));
        let bn = new BN(0);
        let bn1 = optionsLen[1];
        bn1 = bn1.ushln(64);
        bn = bn.add(bn1);
        let bn2 = optionsLen[2];
        bn2 = bn2.ushln(128);
        bn = bn.add(bn2);
        console.log(bn.toString(16));
        await options.setPhaseOccupiedCollateral(bn);
        await OptionsManger.setPhaseSharedPayment(bn);
        result = await options.getTotalOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTotalCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getLeftCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTokenNetworth();
        
        console.log("4-----------------------------------",result.toString(10));
        await OptionsManger.redeemCollateral(498500000000000,collateral0);
        result = await options.getTotalOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTotalCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getLeftCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTokenNetworth();
        console.log("5-----------------------------------",result.toString(10));
        await OptionsManger.redeemCollateral(498500000000000,fnx.address);
        result = await options.getTotalOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTotalCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getOccupiedCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getLeftCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getAvailableCollateral();
        console.log(result.toString(10));
        result = await OptionsManger.getTokenNetworth();
        console.log("5-----------------------------------",result.toString(10));
    });
});